server:
  port: 8088

spring:
  datasource:
    druid:
      url: "jdbc:mysql://localhost:3306/test?autoReconnect=true
              &failOverReadOnly=false&useSSL=false&useUnicode=true&characterEncoding=utf-8
              &zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai"
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
